[package]
name = "stylers_test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
stylers_macro = { version = "1.0.0-alpha", path = "../stylers_macro" }
